name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Set up Git user
        run: |
          git config --global user.email "tubex998@gmail.com"
          git config --global user.name "satyam998"

      - name: Create a new branch
        run: |
          git checkout --orphan temp
          git add -A
          git commit -m "Initial commit"
          git branch -D main
          git branch -m main

      - name: Force push to hub
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git push --force https://satyam998:$HF@huggingface.co/spaces/satyam998/luna main